
#line 3 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[157] =
    {   0,
        3,    3,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   63,    1,   62,    3,   58,   29,   39,   24,
       62,    6,   30,   31,   23,   36,   23,   62,   24,    4,
       37,   26,   27,   26,   38,   34,   35,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   32,   62,   33,
       57,   56,   57,   53,   51,   53,    9,    8,   10,    7,
       62,   21,   22,   20,   48,   49,   40,   62,    3,   26,
       28,   25,    4,   59,    5,   54,   50,    0,    4,   61,
       61,   38,   38,   38,   38,   38,   38,    2,   38,   38,
       38,    2,   38,   38,   38,   38,   38,   55,   52,   19,

       18,   11,   12,   13,   14,   15,   16,   17,   47,   41,
       45,   46,   42,   44,   43,    0,    0,   59,   59,   61,
        0,   61,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,    5,    0,   59,   60,   38,   38,
       38,   38,   38,   38,   38,   38,   60,   38,   38,   38,
       38,   38,   38,   38,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    3,    4,    5,
        6,    7,    8,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   10,   11,   12,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   12,   26,   27,
       28,   29,   12,   12,   30,   30,   30,   30,   31,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       32,   33,   34,   12,   35,   36,   37,   38,   39,   40,

       41,   42,   30,   43,   44,   30,   45,   46,   30,   47,
       48,   30,   30,   49,   50,   51,   52,   53,   54,   30,
       30,   30,   55,   56,   57,   12,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    4,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    4,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[167] =
    {   0,
        0,    0,   54,   55,   56,   57,   90,  148,  206,  264,
       66,   69,  257,  353,  353,   59,  353,  228,  353,  353,
      241,  353,  353,  353,  235,  353,   45,   54,   63,   79,
      353,  225,  224,  223,    0,  353,  353,  201,   63,   34,
      203,   19,   41,  207,  193,  198,  202,  353,  188,  353,
      353,  353,  220,  353,  353,  237,  353,  353,  353,  353,
       84,  353,  353,  353,  353,  353,  353,  119,  103,  353,
      353,  353,  103,   91,  147,  353,  353,  114,  151,    0,
       93,    0,  200,  190,  202,  191,  195,  184,  185,  186,
      184,    0,  181,  180,  186,  185,  184,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,   60,  121,  140,  155,    0,
      105,  161,  190,  185,  176,  173,  186,  184,  179,  182,
      166,  166,  176,  158,  174,  165,  169,  116,  158,  158,
      149,  154,  146,  147,  156,  143,  134,  127,  121,  119,
      100,  100,   80,   68,   68,  353,  322,  326,  330,  334,
      338,  340,   83,  344,  348,   60
    } ;

static const flex_int16_t yy_def[167] =
    {   0,
      156,    1,  157,  157,  158,  158,  159,  159,  160,  160,
      161,  161,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  162,
      156,  156,  156,  156,  163,  156,  156,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      164,  156,  156,  156,  156,  156,  156,  165,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  162,  166,
      166,  163,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  163,  163,  163,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  166,
      156,  166,  163,  163,  163,  163,  163,  163,  163,  163,
      163,  163,  163,  163,  156,  156,  156,  156,  163,  163,
      163,  163,  163,  163,  163,  163,  156,  163,  163,  163,
      163,  163,  163,  163,  163,    0,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156
    } ;

static const flex_int16_t yy_nxt[412] =
    {   0,
       14,   15,   15,   16,   17,   15,   15,   15,   16,   18,
       19,   15,   20,   21,   22,   23,   24,   20,   25,   26,
       27,   28,   29,   30,   30,   31,   32,   33,   34,   35,
       35,   36,   15,   37,   35,   14,   35,   38,   39,   40,
       41,   42,   35,   43,   35,   35,   35,   35,   44,   45,
       35,   35,   46,   47,   48,   49,   50,   15,   52,   52,
       55,   55,   69,  120,   90,   72,   91,   69,   73,   73,
       66,   53,   53,   66,   87,   74,   67,   75,   75,   67,
       76,   88,   92,  135,  135,   77,   82,   93,   56,   56,
       15,   57,   57,   57,   58,   57,   57,   15,   68,   84,

       78,   68,   79,   79,   60,   85,   69,  101,   92,   81,
       86,   69,  118,  121,  119,  119,  122,  122,   92,   81,
      102,  103,   61,  110,  116,  104,   73,   73,  136,  136,
      105,  155,  106,  117,  107,   74,  108,   75,   75,  147,
      147,  121,   92,  117,  136,  136,   92,   57,   15,   57,
       57,   57,   58,   57,   57,   15,  111,  147,  147,   92,
      112,  118,   60,  137,  137,  113,  154,  114,   74,  115,
       75,   75,   78,  153,   79,   79,  118,  117,  119,  119,
       61,   81,  138,   92,  122,  122,  138,  117,  136,  136,
      118,   81,  137,  137,  152,  151,   92,  135,  135,  150,

      149,  148,   92,  146,  117,   57,   15,   57,   57,   57,
       62,   57,   57,   15,  117,   92,  145,  144,  143,   92,
       64,  142,  141,  140,   92,   92,  139,  134,  133,  132,
      131,   92,   92,  130,  129,  128,  127,  126,  125,  124,
      123,   99,   98,   71,   97,   96,   95,   94,   89,   83,
       70,   70,   70,   72,   71,   70,  156,  156,  156,  156,
      156,  156,  156,   57,   15,   57,   57,   57,   62,   57,
       57,   15,  156,  156,  156,  156,  156,  156,   64,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,   57,   51,   51,   51,   51,   54,   54,   54,   54,
       59,   59,   59,   59,   63,   63,   63,   63,   65,   65,
       65,   65,   80,   80,  100,  156,  100,  100,  109,  109,
      109,  109,   13,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156
    } ;

static const flex_int16_t yy_chk[412] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,   16,  166,   42,   27,   42,   16,   27,   27,
       11,    3,    4,   12,   40,   28,   11,   28,   28,   12,
       29,   40,   43,  116,  116,   29,  163,   43,    5,    6,
        7,    7,    7,    7,    7,    7,    7,    7,   11,   39,

       30,   12,   30,   30,    7,   39,   69,   61,  155,   30,
       39,   69,   74,   81,   74,   74,   81,   81,  154,   30,
       61,   61,    7,   68,   73,   61,   73,   73,  121,  121,
       61,  153,   61,   73,   61,   78,   61,   78,   78,  138,
      138,  117,  152,   73,  117,  117,  151,    7,    8,    8,
        8,    8,    8,    8,    8,    8,   68,  147,  147,  150,
       68,  118,    8,  118,  118,   68,  149,   68,   75,   68,
       75,   75,   79,  148,   79,   79,  119,   75,  119,  119,
        8,   79,  122,  146,  122,  122,  136,   75,  136,  136,
      137,   79,  137,  137,  145,  144,  143,  135,  135,  142,

      141,  140,  139,  134,  135,    8,    9,    9,    9,    9,
        9,    9,    9,    9,  135,  133,  132,  131,  130,  129,
        9,  128,  127,  126,  125,  124,  123,   97,   96,   95,
       94,   93,   91,   90,   89,   88,   87,   86,   85,   84,
       83,   56,   53,   49,   47,   46,   45,   44,   41,   38,
       34,   33,   32,   25,   21,   18,   13,    0,    0,    0,
        0,    0,    0,    9,   10,   10,   10,   10,   10,   10,
       10,   10,    0,    0,    0,    0,    0,    0,   10,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,  157,  157,  157,  157,  158,  158,  158,  158,
      159,  159,  159,  159,  160,  160,  160,  160,  161,  161,
      161,  161,  162,  162,  164,    0,  164,  164,  165,  165,
      165,  165,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"
#line 5 "lexer.l"
    #include <iostream>
    #include <string.h>
    #include <string>
    #include <fstream>
    #include <cctype>
    #include "../Symbol Table Manager/include.cpp"

    using namespace std;

    // counts
    int line_count = 1;
    int pending_line_inc = 0;
    int error_count = 0;

    // buffer
    string matched_literal;

    char matched_char;
    string matched_str;
    string matched_comment;

    // write files
    ofstream token_file;
    ofstream log_file;

    const int SYM_TABLE_BUCKETS = 10;

    SymbolTable symbol_table(SYM_TABLE_BUCKETS);
    
    void write_token_and_log(string token, string lexeme) {
        token_file << token;
        log_file << "Line No. " << line_count << ": Token " << token << " Lexeme " << lexeme << " found.\n";
    }

    void write_error_log(string log, string lexeme = "") {
        error_count++;
        log_file << "Line No. " << line_count << ": [ERROR] " << log << " Lexeme: " << lexeme << endl;
    }
#line 580 "lex.yy.cc"

#line 582 "lex.yy.cc"

#define INITIAL 0
#define BLOCK_COMMENT 1
#define LINE_COMMENT 2
#define CHAR 3
#define ERR_MULTIPLE_CHAR 4
#define STRING 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 151 "lexer.l"


#line 722 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 157 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 353 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 153 "lexer.l"
{
    write_error_log("Unrecognized character.", YYText());
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 157 "lexer.l"
{
    string token = string("<");
    for (char c : string(YYText())) {
        token += toupper(c);
    }
    token += ">";
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 167 "lexer.l"
{

}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 172 "lexer.l"
{
    string token = string("<CONST_INT,") + string(YYText()) + string(">");
    write_token_and_log(token, YYText());
    symbol_table.insert(YYText(), "CONST_INT");
    log_file << symbol_table;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 179 "lexer.l"
{
    string token = string("<CONST_FLOAT,") + string(YYText()) + string(">");
    write_token_and_log(token, YYText());
    symbol_table.insert(YYText(), "CONST_FLOAT");
    log_file << symbol_table;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 187 "lexer.l"
{
    matched_char = -1; // used fo matching chars
    matched_literal = ""; // used for error lexeme
    BEGIN CHAR;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 193 "lexer.l"
{
    if (matched_char == -1) {
        string lexeme = "''";
        write_error_log("Empty character constant.", lexeme);
    } else {
        string token = string("<CONST_CHAR,") + matched_char + string(">");
        string lexeme = string("'") + matched_literal + string("'");
        write_token_and_log(token, lexeme);
        symbol_table.insert(string(1, matched_char), "CONST_CHAR");
        log_file << symbol_table;
    }

    BEGIN INITIAL;
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 208 "lexer.l"
{
    string lexeme = string("'") + matched_literal;
    write_error_log("Unterminated character.", lexeme);

    line_count++;

    BEGIN INITIAL;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 217 "lexer.l"
{
    write_error_log("Not a valid character.", YYText());
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 221 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = YYText()[0];
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText(); 
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 232 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\a';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 243 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\b';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 254 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\f';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 265 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\n';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 276 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\r';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 287 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\t';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 298 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\v';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 309 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = '\0';
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 320 "lexer.l"
{
    if (matched_char == -1) {
        matched_char = YYText()[1];
        matched_literal += YYText(); // might need if error occurs
    } else {
        matched_literal += YYText();
        BEGIN INITIAL;
        BEGIN ERR_MULTIPLE_CHAR;
    }
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 331 "lexer.l"
{
    string lexeme = string("'") + matched_literal + string("'");
    write_error_log("Multiple character constant error.", lexeme);

    BEGIN INITIAL;
}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 338 "lexer.l"
{
    string lexeme = string("'") + matched_literal;
    write_error_log("Unterminated character.", lexeme);

    line_count++;

    BEGIN INITIAL;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 347 "lexer.l"
{
    matched_literal += YYText();
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 352 "lexer.l"
{
    string token = string("<ADDOP,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 357 "lexer.l"
{
    string token = string("<MULOP,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 362 "lexer.l"
{
    string token = string("<INCOP,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 367 "lexer.l"
{
    string token = string("<RELOP,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 372 "lexer.l"
{
    string token = string("<ASSIGNOP,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 377 "lexer.l"
{
    string token = string("<LOGICOP,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 382 "lexer.l"
{
    string token = string("<NOT,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 387 "lexer.l"
{
    string token = string("<LPAREN,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 392 "lexer.l"
{
    string token = string("<RPAREN,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 397 "lexer.l"
{
    string token = string("<LCURL,") + YYText() + string(">");
    write_token_and_log(token, YYText());
    symbol_table.enter_scope();
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 403 "lexer.l"
{
    string token = string("<RCURL,") + YYText() + string(">");
    write_token_and_log(token, YYText());
    symbol_table.exit_scope();
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 409 "lexer.l"
{
    string token = string("<LTHIRD,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 414 "lexer.l"
{
    string token = string("<RTHIRD,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 419 "lexer.l"
{
    string token = string("<COMMA,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 424 "lexer.l"
{
    string token = string("<SEMICOLON,") + YYText() + string(">");
    write_token_and_log(token, YYText());
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 430 "lexer.l"
{
    string token = string("<ID,") + YYText() + string(">");
    write_token_and_log(token, YYText());
    symbol_table.insert(YYText(), "ID");
    log_file << symbol_table;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 438 "lexer.l"
{
    BEGIN STRING;
    matched_str = "";
    matched_literal = "";
    pending_line_inc = 0;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 445 "lexer.l"
{
    string token = string("<STRING,") + matched_str + string(">");
    string lexeme = string("\"") + matched_literal + string("\"");
    write_token_and_log(token, lexeme);

    line_count += pending_line_inc;

    BEGIN INITIAL;
} 
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 455 "lexer.l"
{
    pending_line_inc++;
    matched_literal += YYText();
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 460 "lexer.l"
{
    matched_str += '\n';
    matched_literal += YYText();
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 465 "lexer.l"
{
    matched_str += '\t';
    matched_literal += YYText();
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 470 "lexer.l"
{
    pending_line_inc++;
    matched_str += '\r';
    matched_literal += YYText();
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 476 "lexer.l"
{
    matched_str += '\b';
    matched_literal += YYText();
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 481 "lexer.l"
{
    matched_str += '\f';
    matched_literal += YYText();
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 486 "lexer.l"
{
    matched_str += YYText()[1];
    matched_literal += YYText();
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 491 "lexer.l"
{
    matched_str += YYText();
    matched_literal += YYText();
}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 496 "lexer.l"
{
    line_count += pending_line_inc; // so error can point to actual line
    string lexeme = string("\"") + matched_literal;
    write_error_log("Unterminated string.", lexeme);

    line_count++;

    BEGIN INITIAL;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 507 "lexer.l"
{
    BEGIN LINE_COMMENT;
    matched_comment = "";
    pending_line_inc = 0;
}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 513 "lexer.l"
{
    string token = "<COMMENT," + matched_comment + string(">");
    string lexeme = "//" + matched_comment;
    write_token_and_log(token, lexeme);

    line_count += pending_line_inc + 1;
    pending_line_inc = 0;

    BEGIN INITIAL;
}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 524 "lexer.l"
{
    pending_line_inc++;
    matched_comment += YYText();
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 529 "lexer.l"
{
    matched_comment += YYText();
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 534 "lexer.l"
{
    BEGIN BLOCK_COMMENT;
    matched_comment = "";
    pending_line_inc = 0;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 540 "lexer.l"
{
    string token = "<COMMENT," + matched_comment + string(">");
    string lexeme = string("\\**") + matched_comment + string("**\\");
    write_token_and_log(token, lexeme);

    line_count += pending_line_inc;

    BEGIN INITIAL;
}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 550 "lexer.l"
{
    pending_line_inc++;
}
	YY_BREAK
case YY_STATE_EOF(BLOCK_COMMENT):
#line 554 "lexer.l"
{
    string lexeme = string("\\**") + matched_comment;
    write_error_log("Unterminated comment.", lexeme);

    line_count += pending_line_inc;
    pending_line_inc = 0;

    BEGIN INITIAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 564 "lexer.l"
{
    matched_comment += YYText();
}
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 569 "lexer.l"
{
    line_count++;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 573 "lexer.l"
{
    write_error_log("Too many decimals.", YYText());    
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 577 "lexer.l"
{
    write_error_log("Ill formed number.", YYText());
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 581 "lexer.l"
{
    write_error_log("Invalid suffix on numberic constant or invalid prefix on identifier.", YYText());
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 586 "lexer.l"
ECHO;
	YY_BREAK
#line 1400 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(ERR_MULTIPLE_CHAR):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 58);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 157 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 58;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 157 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 156);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 586 "lexer.l"



int main(int argc, char* argv[]) {
    if (argc != 4) {
        cout << "ERROR: lexer needs input, token, log file names as argument\n";
        return 0;
    }

    ifstream input_file(argv[1]);
    token_file.open(argv[2]);
    log_file.open(argv[3]);

    if (!input_file || !token_file || !log_file) {
        cout << "ERROR: Could not open file\n";
        return 0;
    }

    yyFlexLexer lexer(&input_file);
    while (lexer.yylex()) {}

    log_file << "Total lines: " << line_count << endl;
    log_file << "Total errors: " << error_count; 

    input_file.close();
    token_file.close();
    log_file.close();

    return 0;
}

